name: animated_clock_indicator
description: "A customizable animated clock indicator widget for Flutter, allowing developers to add visually appealing, configurable clock animations to their applications."

version: 1.0.3
homepage: https://github.com/nkalahanov/animated_clock_indicator
repository: https://github.com/nkalahanov/animated_clock_indicator

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
keywords:
  - animated clock
  - animated clock indicator
  - customizable clock
  - loading clock
  - clock animation
  - message clock
  - message loading
  - message sending

license: "MIT"
